Repository markus-wa/demoinfocs-golang, pull requests merged in 2020-03, with the labels that each got.

#188 implement fallback to CSVCMsg_ServerInfo for tick rate info
  common/common.go
  common/common_test.go
  common/player.go
  convars.go
  fake/parser.go
  net_messages.go
  parser.go
  parser_interface.go
  parser_test.go
  parsing.go
Labels: enhancement

#189 core: don't panic, return errors instead
  datatables.go
  demoinfocs_test.go
  game_events.go
  net_messages.go
  parser_test.go
  parsing.go
  stringtables.go
Labels: bug

#191 core: don't suppress ConsumerCodePanic in recoverFromPanic
  go.mod
  go.sum
  parser.go
  parser_test.go
  parsing.go
Labels: enhancement

#196 ci: remove obsolete "sudo: required" from .travis.yml
  .travis.yml
Labels: technical debt

#197 changing the existing weapon instead of creating a new one
  datatables.go
Labels: bug, needs changes
